backend:
    name: git-gateway
    branch: main
    site_domain: kinetiatest.netlify.app

media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "desc", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
